name: MapsPlugin
main: com.oresomecraft.maps.MapsPlugin
version: 1.0
softdepend: [OresomeBattles]
commands:
   enablemaps:
      description: Loads maps of a specific type
      usage: /<command> <battle/arcade>
      permission: oresomebattles.admin
      permission-message: You don't have <permission>